package com.simon.voiceime;
import android.graphics.Rect;import android.os.*;import android.view.*;import org.json.*;import java.io.File;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;import androidx.test.platform.app.InstrumentationRegistry;
/** Diagnostic: fixed offered load, no per-key frame wait. Missing intermediate frames remain explicit. */
public class FixedCadence670AndroidTest extends KeyLatency670AndroidTest {
 ViewTreeObserver.OnPreDrawListener preObserver;
 public void testFixedCadence()throws Exception{
  ready();out=new File(inst.getTargetContext().getFilesDir(),"v666");out.mkdirs();startEndpoint();
  int length=Integer.parseInt(InstrumentationRegistry.getArguments().getString("length","45"));String[] base={"ㄐㄧㄣ ","ㄊㄧㄢ ","ㄨㄛˇ","ㄇㄣ˙","ㄧˋ","ㄑㄧˇ","ㄊㄠˇ","ㄌㄨㄣˋ","ㄐㄧˋ","ㄏㄨㄚˋ"};StringBuilder sequence=new StringBuilder();for(int n=0;n<length;n++)sequence.append(base[n%10]);
  int warm=Integer.parseInt(InstrumentationRegistry.getArguments().getString("warm","0"));for(int n=0;n<warm;n++)for(char cp:base[n%10].toCharArray())tap(cp==' '?"空白":String.valueOf(cp));if(warm>0){tap("↵");inst.waitForIdleSync();Thread.sleep(1500);}
  final long[] down=new long[sequence.length()];AtomicInteger observed=new AtomicInteger();JSONArray frames=new JSONArray();CountDownLatch last=new CountDownLatch(1);Map<Character,Rect> bounds=new HashMap<>();Map<Character,View> keyViews=new HashMap<>();
  for(char cp:sequence.toString().toCharArray())if(!bounds.containsKey(cp)){Rect r=new Rect();await(cp==' '?"空白":String.valueOf(cp)).getBoundsInScreen(r);bounds.put(cp,r);}
  inst.runOnMainSync(()->{try{bindWindow();android.content.Context c=row1.getContext();while(!(c instanceof SimonIMEService)&&c instanceof android.content.ContextWrapper)c=((android.content.ContextWrapper)c).getBaseContext();service=c;controller=SimonIMEService.class.getDeclaredField("zhuyinInput");controller.setAccessible(true);assertTrue(root.isHardwareAccelerated());for(char cp:new char[]{'ㄠ','ㄟ','ㄨ','ㄧ'})keyViews.put(cp,root.findViewWithTag("key:"+cp));preObserver=()->{int count=keys().length();if(count<=observed.get()||count>down.length)return true;observed.set(count);long submit=System.nanoTime();JSONObject geometry=new JSONObject();try{int[] loc=new int[2];root.getLocationOnScreen(loc);geometry.put("root_x",loc[0]).put("root_y",loc[1]).put("root_height",root.getHeight());for(char cp:new char[]{'ㄠ','ㄟ','ㄨ','ㄧ'}){View kv=keyViews.get(cp);if(kv!=null){int[] kp=new int[2];kv.getLocationOnScreen(kp);Rect kr=new Rect(kp[0],kp[1],kp[0]+kv.getWidth(),kp[1]+kv.getHeight());geometry.put(String.valueOf(cp),new JSONArray().put(kr.left).put(kr.top).put(kr.right).put(kr.bottom));}}}catch(Exception failure){throw new RuntimeException(failure);}root.getViewTreeObserver().registerFrameCommitCallback(()->{try{long commit=System.nanoTime();synchronized(frames){frames.put(new JSONObject().put("geometry",geometry).put("last_key",count-1).put("down_ns",down[count-1]).put("draw_ns",submit).put("frame_commit_ns",commit).put("latency_ms",(commit-down[count-1])/1e6));}if(count==down.length)last.countDown();}catch(Exception failure){throw new RuntimeException(failure);}});return true;};root.getViewTreeObserver().addOnPreDrawListener(preObserver);}catch(Exception failure){throw new RuntimeException(failure);}});
  boolean direct="direct".equals(InstrumentationRegistry.getArguments().getString("injector","automation"));Object injectionOwner;java.lang.reflect.Method injector;
  if(direct){ui.adoptShellPermissionIdentity("android.permission.INJECT_EVENTS");Class<?> manager=Class.forName("android.hardware.input.InputManagerGlobal");injectionOwner=manager.getDeclaredMethod("getInstance").invoke(null);injector=manager.getDeclaredMethod("injectInputEvent",InputEvent.class,int.class);}else{injectionOwner=ui;injector=android.app.UiAutomation.class.getDeclaredMethod("injectInputEvent",InputEvent.class,boolean.class,boolean.class);}injector.setAccessible(true);
  Thread.sleep(1500);shell("dumpsys gfxinfo com.simon.voiceime reset");long start=SystemClock.uptimeMillis();
  for(int i=0;i<down.length;i++){long deadline=start+i*197;long rest=deadline-SystemClock.uptimeMillis();if(rest>0)Thread.sleep(rest);char cp=sequence.charAt(i);Rect r=bounds.get(cp);long t=SystemClock.uptimeMillis();down[i]=System.nanoTime();android.os.Trace.beginSection("D670.inject."+i);try{MotionEvent d=MotionEvent.obtain(t,t,0,r.centerX(),r.centerY(),0),u=MotionEvent.obtain(t,t+20,1,r.centerX(),r.centerY(),0);assertTrue(direct?((Boolean)injector.invoke(injectionOwner,d,0)&&(Boolean)injector.invoke(injectionOwner,u,0)):((Boolean)injector.invoke(ui,d,false,false)&&(Boolean)injector.invoke(ui,u,false,false)));d.recycle();u.recycle();}finally{android.os.Trace.endSection();}}
  boolean finalFrame=last.await(15,TimeUnit.SECONDS);int drain=Integer.parseInt(InstrumentationRegistry.getArguments().getString("drain_ms","3000"));Thread.sleep(drain);JSONArray sends=new JSONArray();for(int i=0;i<down.length;i++)sends.put(new JSONObject().put("key",i).put("down_ns",down[i]));
  final String[] finalKeys={null};inst.runOnMainSync(()->finalKeys[0]=keys());
  JSONObject planned=new JSONObject();for(Map.Entry<Character,Rect> entry:bounds.entrySet()){Rect r=entry.getValue();planned.put(String.valueOf(entry.getKey()),new JSONArray().put(r.left).put(r.top).put(r.right).put(r.bottom));}
  save("fixed-cadence.json",new JSONObject().put("planned_bounds",planned).put("characters",length).put("drain_ms",drain).put("warm_characters",warm).put("expected_keys",sequence.toString()).put("actual_keys",finalKeys[0]).put("input_matches",sequence.toString().equals(finalKeys[0])).put("cadence_ms",197).put("injector",direct?"InputManagerGlobal ASYNC, no automation surface barrier":"UiAutomation ASYNC, waitForAnimations=false").put("sent",sends).put("frames",frames).put("final_frame",finalFrame).put("observed_key_count",observed.get()).toString());
  save("framestats.txt",shell("dumpsys gfxinfo com.simon.voiceime framestats"));assertTrue("final composition must reach a frame",finalFrame);assertEquals("offered physical keys must equal native composition keys",sequence.toString(),finalKeys[0]);
 }
 @Override protected void tearDown()throws Exception{if(root!=null&&preObserver!=null)inst.runOnMainSync(()->root.getViewTreeObserver().removeOnPreDrawListener(preObserver));super.tearDown();}
}
