package com.simon.voiceime;
import android.view.*;import android.os.*;import android.graphics.Rect;import android.widget.*;import androidx.test.platform.app.InstrumentationRegistry;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;
/** Real IME input/window on an owned, egress-blocked emulator; HTTP only to loopback. */
public class T9Keyboard682AndroidTest extends TapCursor677AndroidTest {
 SimonIMEService service;T9Keyboard page;String stub="correct";int requests;JSONObject lastRequest;
 @Override void preparePreferences(){super.preparePreferences();inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0).edit().putBoolean("t9_mode",false).commit();}
 void start()throws Exception{ready();out=new File(inst.getTargetContext().getFilesDir(),"v666");out.mkdirs();bind();
  inst.runOnMainSync(()->{android.content.Context c=words.getContext();while(c instanceof android.content.ContextWrapper&&!(c instanceof SimonIMEService))c=((android.content.ContextWrapper)c).getBaseContext();service=(SimonIMEService)c;});
  text("");tap("test_input");tap("九");await("T9 4");
  inst.runOnMainSync(()->{try{var f=SimonIMEService.class.getDeclaredField("t9Page");f.setAccessible(true);page=(T9Keyboard)f.get(service);}catch(Exception e){throw new RuntimeException(e);}});
  long deadline=SystemClock.uptimeMillis()+30000;while(SystemClock.uptimeMillis()<deadline){final boolean[] ready={false};inst.runOnMainSync(()->{try{var f=T9Keyboard.class.getDeclaredField("ready");f.setAccessible(true);ready[0]=f.getBoolean(page);}catch(Exception e){throw new RuntimeException(e);}});if(ready[0])return;Thread.sleep(50);}fail("local engine did not initialize");
 }
 String codes(){final String[] value={null};inst.runOnMainSync(()->value[0]=page.core.codes());return value[0];}
 String preview(){final String[] value={null};inst.runOnMainSync(()->value[0]=((TextView)page.view().findViewWithTag("t9-preview")).getText().toString());return value[0];}
 void waitPreview()throws Exception{
  // A nonempty preview may still belong to the previous key; await worker and UI publication.
  var field=T9Keyboard.class.getDeclaredField("worker");field.setAccessible(true);var worker=(java.util.concurrent.ExecutorService)field.get(page);
  java.util.concurrent.CountDownLatch decoded=new java.util.concurrent.CountDownLatch(1);worker.execute(()->page.view().post(decoded::countDown));assertTrue("current local decode published",decoded.await(10,java.util.concurrent.TimeUnit.SECONDS));
  long deadline=SystemClock.uptimeMillis()+10000;while(SystemClock.uptimeMillis()<deadline){if(!preview().isEmpty()&&!preview().contains("載入"))return;Thread.sleep(30);}fail("preview unavailable for "+codes());}
 void t9(int key)throws Exception{tap(key==10?"T9 分音節":key==11?"T9 刪除":"T9 "+key);}
 Rect keyRect(int key){final Rect r=new Rect();inst.runOnMainSync(()->{View v=page.view().findViewWithTag("key:t9:"+key);int[] at=new int[2];v.getLocationOnScreen(at);r.set(at[0],at[1],at[0]+v.getWidth(),at[1]+v.getHeight());});return r;}
 void report(String name)throws Exception{save(name,new JSONObject().put("codes",codes()).put("preview",preview()).put("editor",editorText(await("test_input"))).toString());}
 public void testToggleColdAndStates()throws Exception{
  start();screenshot("t9-start");for(int i=0;i<10;i++){tap("注");await("九");tap("九");await("T9 4");}assertEquals("",codes());
  t9(4);inst.runOnMainSync(()->assertEquals(1<<7,page.core.mask()));screenshot("t9-after4");t9(7);inst.runOnMainSync(()->{assertEquals(0,page.core.mask()&(1<<7));for(int k:new int[]{8,9,0,10})assertTrue((page.core.mask()&(1<<k))!=0);});screenshot("t9-after47");report("states-text.json");assertEquals("",editorText(await("test_input")));
 }
 public void testReplay20AndDirectDigits()throws Exception{
  start();String fixture=new String(inst.getContext().getAssets().open("t9-heldout.tsv").readAllBytes(),StandardCharsets.UTF_8);JSONArray results=new JSONArray(),observed=new JSONArray();
  for(String line:fixture.split("\n")){String[] pair=line.split("\t");String expected=pair[1];inst.runOnMainSync(()->page.clear());for(String code:expected.split(" ")){if(!codes().isEmpty())t9(10);for(char k:code.toCharArray())t9(k-'0');}waitPreview();String draft=preview();observed.put(new JSONObject().put("gold",pair[0]).put("expected",expected).put("codes",codes()).put("draft",draft).put("preview",preview()));save("replay20-observed.json",observed.toString());assertEquals(expected,codes());assertEquals("",editorText(await("test_input")));inst.runOnMainSync(()->assertTrue(page.core.legal(draft,expected)));tap("空白");assertEquals(draft,editorText(await("test_input")));results.put(new JSONObject().put("gold",pair[0]).put("codes",expected).put("draft",draft).put("committed",editorText(await("test_input"))));text("");tap("test_input");}
  Rect r=keyRect(3);long t=SystemClock.uptimeMillis();MotionEvent d=MotionEvent.obtain(t,t,0,r.centerX(),r.centerY(),0),u=MotionEvent.obtain(t,t+500,1,r.centerX(),r.centerY(),0);ui.injectInputEvent(d,true);Thread.sleep(500);ui.injectInputEvent(u,true);d.recycle();u.recycle();Thread.sleep(200);assertEquals("3",editorText(await("test_input")));save("replay20.json",results.toString());report("digit-direct-text.json");screenshot("digit-direct");
 }
 public void testReassignNearFar()throws Exception{
  start();t9(4);Rect dimmed=keyRect(8);tap(new Rect(dimmed.left+3,dimmed.centerY(),dimmed.left+4,dimmed.centerY()+1));Thread.sleep(200);assertEquals("47",codes());inst.runOnMainSync(()->page.clear());t9(4);tap(keyRect(3));Thread.sleep(200);assertEquals("4",codes());report("reassign-text.json");screenshot("reassign");
 }
 void multi(long down,int action,Rect a,Rect b,int count)throws Exception{
  MotionEvent.PointerProperties[] properties=new MotionEvent.PointerProperties[count];MotionEvent.PointerCoords[] coords=new MotionEvent.PointerCoords[count];for(int i=0;i<count;i++){properties[i]=new MotionEvent.PointerProperties();properties[i].id=i;properties[i].toolType=MotionEvent.TOOL_TYPE_FINGER;coords[i]=new MotionEvent.PointerCoords();coords[i].x=(i==0?a:b).centerX();coords[i].y=(i==0?a:b).centerY();coords[i].pressure=1;coords[i].size=1;}
  MotionEvent e=MotionEvent.obtain(down,SystemClock.uptimeMillis(),action,count,properties,coords,0,0,1,1,0,0,android.view.InputDevice.SOURCE_TOUCHSCREEN,0);try{assertTrue(ui.injectInputEvent(e,true));}finally{e.recycle();}
 }
 public void testOverlappingPointers()throws Exception{start();Rect a=keyRect(4),b=keyRect(7);long time=SystemClock.uptimeMillis();multi(time,0,a,b,1);Thread.sleep(20);multi(time,5|(1<<8),a,b,2);Thread.sleep(30);multi(time,6|(1<<8),a,b,2);Thread.sleep(20);multi(time,1,a,b,1);Thread.sleep(250);assertEquals("47",codes());report("overlap-text.json");screenshot("overlap");}
 @Override void startEndpoint()throws Exception{
  endpoint=new ServerSocket(8181,8,InetAddress.getByName("127.0.0.1"));server=new Thread(()->{while(!stop)try(Socket s=endpoint.accept()){s.setSoTimeout(5000);InputStream in=new BufferedInputStream(s.getInputStream());String first=line(in);int size=0;for(String h;!(h=line(in)).isEmpty();)if(h.toLowerCase().startsWith("content-length:"))size=Integer.parseInt(h.substring(15).trim());String content=new String(in.readNBytes(size),StandardCharsets.UTF_8);String response="{}";int code=404;
   if(first.startsWith("POST /v1/ime/sentence-candidates ")){JSONObject req=new JSONObject(content);lastRequest=req;requests++;if("t9_sentence".equals(req.optString("kind"))){String mode=stub;String draft=req.getString("draft");int epoch=req.getInt("epoch");if(mode.equals("timeout")){Thread.sleep(8500);continue;}String sentence=mode.equals("illegal")?"XYZ":draft+"。";String source=mode.equals("low")?"local":mode.equals("jev")?"jev":"gemini";response=new JSONObject().put("epoch",epoch-(mode.equals("stale")?1:0)).put("sentence",sentence).put("source",source).put("confidence",mode.equals("low")?.5:.8).put("illegal_positions",0).toString();code=200;}}
   byte[] body=response.getBytes(StandardCharsets.UTF_8);s.getOutputStream().write(("HTTP/1.1 "+code+" Fixture\r\nContent-Type: application/json\r\nContent-Length: "+body.length+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));s.getOutputStream().write(body);s.getOutputStream().flush();
  }catch(SocketException e){}catch(Exception e){if(!stop)error=e;}},"T9LoopbackStub");server.start();
 }
 String ai(){final String[] value={null};inst.runOnMainSync(()->{try{var f=T9Keyboard.class.getDeclaredField("ai");f.setAccessible(true);value[0]=(String)f.get(page);}catch(Exception e){throw new RuntimeException(e);}});return value[0];}
 public void testAiAndJevStubs()throws Exception{
  start();startEndpoint();JSONArray results=new JSONArray();for(String mode:new String[]{"correct","stale","illegal","low","jev","timeout"}){stub=mode;inst.runOnMainSync(()->page.clear());t9(4);t9(7);waitPreview();int before=requests;long deadline=SystemClock.uptimeMillis()+6000;while(requests==before&&SystemClock.uptimeMillis()<deadline)Thread.sleep(30);Thread.sleep(mode.equals("timeout")?8500:300);boolean shown=mode.equals("correct")||mode.equals("jev");assertEquals(mode,shown,!ai().isEmpty());assertEquals("no automatic commit","",editorText(await("test_input")));if(mode.equals("low"))assertNotNull("low confidence keeps Draft punctuation",node("T9 句 "+lastRequest.getString("draft")+"。"));results.put(new JSONObject().put("mode",mode).put("ai",ai()).put("requests",requests));if(mode.equals("correct")){String suggestion=ai();tap("T9 AI "+suggestion);assertEquals(suggestion,editorText(await("test_input")));text("");tap("test_input");}}
  stop=true;endpoint.close();server.join(1000);endpoint=null;inst.runOnMainSync(()->page.clear());t9(4);t9(7);waitPreview();Thread.sleep(1000);assertEquals("",ai());results.put(new JSONObject().put("mode","offline").put("local",preview()));save("ai-stub-results.json",results.toString());report("ai-text.json");screenshot("ai-stubs");
 }
 public void testPersonalOrderAndReset()throws Exception{start();t9(4);t9(7);waitPreview();String before=preview();LinearLayout row=(LinearLayout)page.view().findViewWithTag("t9-characters");final String[] selected={null};inst.runOnMainSync(()->{TextView item=(TextView)row.getChildAt(1);selected[0]=item.getText().toString();item.performClick();});String chosen=preview();assertEquals(selected[0],chosen);tap("空白");inst.runOnMainSync(()->page.clear());t9(4);t9(7);waitPreview();assertEquals(chosen,preview());inst.runOnMainSync(()->{var prefs=inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0);var e=prefs.edit();for(String k:prefs.getAll().keySet())if(k.startsWith("t9_learning_"))e.remove(k);e.commit();page.clear();});t9(4);t9(7);waitPreview();assertEquals(before,preview());report("personal-reset-text.json");screenshot("personal-reset");}
 public void testDisplayAndSnapshot()throws Exception{
  start();t9(4);t9(7);String before=codes();JSONArray labels=new JSONArray();inst.runOnMainSync(()->{page.reconfigure();assertEquals(before,page.core.codes());for(int k=0;k<=10;k++){TextView v=(TextView)page.view().findViewWithTag("key:t9:"+k);assertNotNull(v);if(v.getLayout()!=null){int required=v.getLayout().getHeight();int content=v.getHeight()-v.getTotalPaddingTop()-v.getTotalPaddingBottom();try{labels.put(new JSONObject().put("key",k).put("required",required).put("content",content).put("width",v.getWidth()).put("height",v.getHeight()));}catch(Exception e){throw new RuntimeException(e);}assertTrue("key "+k+" label vertically clipped",content>=required);}}});save("t9-labels.json",labels.toString());report("display-text.json");screenshot("t9-display");
 }
 public void testProtectedField()throws Exception{
  start();startEndpoint();int before=requests;shell("am force-stop com.ime.sandbox.testpad");shell("am start -W -n com.ime.sandbox.testpad/.MainActivity --ei input_type 129");tap("test_input");Thread.sleep(600);inst.runOnMainSync(()->{assertTrue("actual password EditorInfo",(service.getCurrentInputEditorInfo().inputType&0xfff)==129);assertFalse(service.t9Allowed());page.key(4,false,0,0);page.key(7,false,0,0);});Thread.sleep(1600);assertEquals("protected input never sends",before,requests);assertEquals("",ai());assertEquals("",editorText(await("test_input")));report("protected-text.json");screenshot("protected");
 }
 // Landscape uses Android's extracted editor; the app editor is not an accessibility window.
 String foldEditorText(){final String[] value={null};inst.runOnMainSync(()->{var ic=service.getCurrentInputConnection();assertNotNull(ic);CharSequence before=ic.getTextBeforeCursor(1000,0),after=ic.getTextAfterCursor(1000,0);assertNotNull(before);assertNotNull(after);value[0]=before.toString()+after.toString();});return value[0];}
 public void testSizesMidComposition()throws Exception{
  start();t9(4);t9(7);waitPreview();String size=shell("wm size"),density=shell("wm density"),font=shell("settings get system font_scale");JSONArray steps=new JSONArray();
  try {int index=0;for(String dimensions:new String[]{"968x2376","1856x2160","2160x1856","1856x2160","968x2376"}){
   JSONObject step=new JSONObject().put("size_before",shell("wm size")).put("density_before",shell("wm density")).put("font_before",shell("settings get system font_scale")).put("codes_before",codes()).put("preview_before",preview());
   shell("wm size "+dimensions);shell("wm density 420");shell("settings put system font_scale 1.3");Thread.sleep(1800);waitPreview();
   assertEquals("composition survives actual configuration","47",codes());assertEquals("preview survives configuration",step.getString("preview_before"),preview());assertEquals("no partial commit","",foldEditorText());
   String display=dimensions.equals("968x2376")?"cover":dimensions.equals("1856x2160")?"inner":"landscape";
   step.put("size_after",shell("wm size")).put("density_after",shell("wm density")).put("font_after",shell("settings get system font_scale")).put("codes_after",codes()).put("preview_after",preview()).put("display",display);
   assertTrue(step.getString("size_after").contains(dimensions));assertTrue(step.getString("density_after").contains("420"));assertEquals("1.3",step.getString("font_after").trim());checkLabels();
   t9(11);t9(11);assertEquals("",codes());for(int k:new int[]{4,7,0,10,3,7,0})t9(k);waitPreview();assertEquals("470 370",codes());String draft=preview();inst.runOnMainSync(()->assertTrue(page.core.legal(draft,"470 370")));assertEquals("",foldEditorText());screenshot("size-"+display+"-"+(index++));tap("空白");assertEquals(draft,foldEditorText());step.put("draft",draft).put("committed",foldEditorText());
   inst.runOnMainSync(()->{var ic=service.getCurrentInputConnection();assertNotNull(ic);assertTrue(ic.deleteSurroundingText(1000,1000));});assertEquals("",foldEditorText());t9(4);t9(7);waitPreview();steps.put(step);save("size-switches.json",steps.toString());
  }}finally {String value=size.contains("Override size:")?size.split("Override size:")[1].trim():"reset";String dpi=density.contains("Override density:")?density.split("Override density:")[1].trim():"reset";shell("wm size "+value);shell("wm density "+dpi);shell("settings put system font_scale "+font.trim());Thread.sleep(1000);save("size-restored.json",new JSONObject().put("size",shell("wm size")).put("density",shell("wm density")).put("font",shell("settings get system font_scale")).toString());}
  save("size-switch-text.json",new JSONObject().put("codes",codes()).put("preview",preview()).put("editor",foldEditorText()).toString());
 }
 void checkLabels(){inst.runOnMainSync(()->{for(int k=0;k<=10;k++){TextView v=(TextView)page.view().findViewWithTag("key:t9:"+k);assertNotNull(v);assertTrue("visible key "+k,v.isShown());android.graphics.Rect clip=new android.graphics.Rect();assertTrue(v.getGlobalVisibleRect(clip));assertEquals("full key below insets",v.getHeight(),clip.height());if(v.getLayout()!=null){assertTrue("label "+k,v.getHeight()-v.getTotalPaddingTop()-v.getTotalPaddingBottom()>=v.getLayout().getHeight());assertTrue("two lines "+k,v.getLayout().getLineCount()<=2);String first=v.getText().toString().split("\n",2)[0];android.graphics.Rect glyph=new android.graphics.Rect();v.getPaint().getTextBounds(first,0,first.length(),glyph);assertTrue("horizontal glyph "+k,glyph.width()<=v.getWidth()-v.getTotalPaddingLeft()-v.getTotalPaddingRight());}}});}
 public void testPendingDecodeAcrossConfiguration()throws Exception{
  start();java.util.concurrent.CountDownLatch entered=new java.util.concurrent.CountDownLatch(1),release=new java.util.concurrent.CountDownLatch(1);
  var field=T9Keyboard.class.getDeclaredField("worker");field.setAccessible(true);var worker=(java.util.concurrent.ExecutorService)field.get(page);
  worker.execute(()->{entered.countDown();try{release.await();}catch(InterruptedException e){Thread.currentThread().interrupt();}});assertTrue(entered.await(3,java.util.concurrent.TimeUnit.SECONDS));
  try{inst.runOnMainSync(()->{page.key(4,false,0,0);page.key(7,false,0,0);page.reconfigure();});}finally{release.countDown();}
  waitPreview();assertEquals("47",codes());report("pending-decode-text.json");
 }
 public void testWaitPreviewUsesCurrentDecode()throws Exception{
  start();t9(4);t9(7);waitPreview();String previous=preview();
  java.util.concurrent.CountDownLatch entered=new java.util.concurrent.CountDownLatch(1),release=new java.util.concurrent.CountDownLatch(1);
  var field=T9Keyboard.class.getDeclaredField("worker");field.setAccessible(true);var worker=(java.util.concurrent.ExecutorService)field.get(page);
  worker.execute(()->{entered.countDown();try{release.await();}catch(InterruptedException e){Thread.currentThread().interrupt();}});assertTrue(entered.await(3,java.util.concurrent.TimeUnit.SECONDS));
  try{inst.runOnMainSync(()->page.key(0,false,0,0));new Thread(()->{try{Thread.sleep(300);}catch(InterruptedException e){Thread.currentThread().interrupt();}finally{release.countDown();}}).start();
   long started=SystemClock.uptimeMillis();waitPreview();String current=preview();save("decode-readiness.json",new JSONObject().put("previous",previous).put("expected","470").put("codes",codes()).put("draft",current).put("wait_ms",SystemClock.uptimeMillis()-started).put("worker_released",release.getCount()==0).toString());assertEquals("470",codes());inst.runOnMainSync(()->assertTrue(page.core.legal(current,"470")));
  }finally{release.countDown();}
 }
 public void testCoreBudgets()throws Exception{inst=InstrumentationRegistry.getInstrumentation();out=new File(inst.getTargetContext().getFilesDir(),"v666");out.mkdirs();long libraryResidentBefore=android.os.Debug.getPss();Class.forName("com.simon.voiceime.t9.T9Core");long libraryResident=android.os.Debug.getPss()-libraryResidentBefore;long residentBefore=android.os.Debug.getPss();long before=android.os.Debug.getNativeHeapAllocatedSize(),started=System.nanoTime();try(com.simon.voiceime.t9.T9Core core=new com.simon.voiceime.t9.T9Core()){long load=System.nanoTime()-started,heap=android.os.Debug.getNativeHeapAllocatedSize()-before;long resident=android.os.Debug.getPss()-residentBefore;List<Long> times=new ArrayList<>();for(int i=0;i<1000;i++){core.clear();long t=System.nanoTime();assertTrue(core.push(4));times.add(System.nanoTime()-t);}Collections.sort(times);save("core-budgets.json",new JSONObject().put("load_ms",load/1e6).put("heap_delta",heap).put("resident_pss_delta_kib",resident).put("library_load_pss_delta_kib",libraryResident).put("push_p50_us",times.get(500)/1e3).put("push_p95_us",times.get(950)/1e3).toString());assertTrue("push under 50 us",times.get(950)<50000);assertTrue("load under 30 ms",load<30000000);assertTrue("table heap below 3MB",heap<3000000);assertTrue("table resident below 3MB",resident*1024<3000000);}ready();bind();screenshot("core-budget-editor");readback("core-budget-text.json");}
}
