package com.simon.voiceime;
import org.json.JSONObject;
public class UpgradeSafety670AndroidTest extends LivePause670AndroidTest {
 boolean upgrade, explicitOff;
 @Override void preparePreferences(){super.preparePreferences();if(upgrade)inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0).edit().putBoolean("auto_correction",true).putString("ai_sentence_mode","live").remove("ai_sentence_auto_apply").remove("ai_auto_apply_migration_version").commit();}
 @Override void ready()throws Exception {if(upgrade)readyWithoutOptIn();else {super.ready();if(explicitOff)inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0).edit().putBoolean("ai_sentence_auto_apply",false).commit();}}
 void noChange(String label)throws Exception {begin();typeWrong();String original=shown();String editor=String.valueOf(await("test_input").getText());Thread.sleep(2200);save(label+".json",new JSONObject().put("before",original).put("after",shown()).put("requests",requestCount).put("diagnostic",new JSONObject(diagnostic())).toString());assertTrue("fixture reached",requestCount>0);assertTrue("valid response reached application gate",new JSONObject(diagnostic()).getLong("validation")>=0);assertEquals("known wrong original","墮於",original);assertEquals("automatic proposal must not change preview",original,shown());assertEquals("editor unchanged",editor,String.valueOf(await("test_input").getText()));assertFalse(highlighted());tap("↵");assertEquals("Enter preserves original",original,String.valueOf(await("test_input").getText()));}
 public void testMissingProtectedNeverApplies()throws Exception {candidateProtected=null;noChange("missing-protected");}
 public void testMissingServerProtectionNeverApplies()throws Exception {protectionReady=null;noChange("server-protection-missing");}
 public void testServerProtectionFalseNeverApplies()throws Exception {protectionReady=false;noChange("server-protection-false");}
 public void testExplicitOffNeverApplies()throws Exception {explicitOff=true;noChange("explicit-off");}
 public void testMigrationOnlyOnce()throws Exception {begin();android.content.SharedPreferences p=inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0);p.edit().putBoolean("auto_correction",false).putBoolean("ai_sentence_auto_apply",true).commit();shell("am start -W -n com.simon.voiceime/.SettingsActivity");Thread.sleep(500);assertEquals(670,p.getInt("ai_auto_apply_migration_version",0));assertTrue("later explicit opt-in survives another entry",p.getBoolean("ai_sentence_auto_apply",false));assertFalse(p.getBoolean("auto_correction",false));save("migration-once.json",new JSONObject().put("version",670).put("opt_in_preserved",true).toString());}
 public void testUpgradeDisablesInheritedLive()throws Exception {upgrade=true;noChange("upgrade");android.content.SharedPreferences p=inst.getTargetContext().getSharedPreferences("simon_ime_prefs",0);assertFalse("old setting cleared",p.getBoolean("auto_correction",false));assertEquals(670,p.getInt("ai_auto_apply_migration_version",0));assertEquals("shadow",p.getString("ai_sentence_mode",""));assertFalse(p.getBoolean("ai_sentence_auto_apply",false));}
}
