import com.simon.voiceime.correct.OnDeviceCorrector;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 * JVM self-test for {@link OnDeviceCorrector} — runs WITHOUT an Android device.
 *
 * Loads the §37-filtered APK asset dicts, runs ~50 Traditional-Chinese legal dictation cases
 * (golden expectations generated by tools/gen_selftest_corpus.py at server parity), and verifies:
 *   - 簡→繁 conversion (s2tw glyph, NOT s2twp)
 *   - the legal overrides (係爭→系爭, 程序 stays 程序, 准/準, 法律程序)
 *   - paraformer + legal_dict mishear fixes
 *   - protected-term no-touch
 *   - filler removal
 *   - the 改字 GUARD: a stub punctuator that ALTERS a character must be discarded (fallback to
 *     step-4 text); a stub that only ADDS punctuation must be accepted.
 *
 * Exit code 0 = all pass; non-zero = failures.
 */
public class OnDeviceCorrectorSelfTest {

    static final Path ASSETS = Paths.get("app/src/main/assets/correction");
    static final Path CORPUS = Paths.get("app/src/test/resources/selftest_corpus.tsv");

    public static void main(String[] args) throws Exception {
        OnDeviceCorrector corrector;
        try (InputStream para = in("paraformer_legal.txt");
             InputStream stp = in("opencc/STPhrases.txt");
             InputStream stc = in("opencc/STCharacters.txt");
             InputStream twv = in("opencc/TWVariants.txt");
             InputStream ovr = in("legal_overrides.txt");
             InputStream mis = in("legal_dict_mishear.txt");
             InputStream prot = in("protected_terms.txt")) {
            corrector = OnDeviceCorrector.load(para, stp, stc, twv, ovr, mis, prot);
        }

        List<String[]> rows = loadCorpus();
        int total = 0, pass = 0, fail = 0;
        List<String> failures = new ArrayList<>();

        // --- deterministic CASE rows (steps 1-4, no punctuation) ---
        for (String[] r : rows) {
            if (!"CASE".equals(r[0])) continue;
            total++;
            String input = r[1], expected = r[2];
            String got = corrector.correctDeterministic(input);
            if (expected.equals(got)) {
                pass++;
            } else {
                fail++;
                failures.add("CASE  in=[" + input + "]\n      exp=[" + expected + "]\n      got=[" + got + "]");
            }
        }

        // --- GUARD rows: feed a character-ALTERING punctuator -> must fall back to step-4 text. ---
        for (String[] r : rows) {
            if (!"GUARD".equals(r[0])) continue;
            String input = r[1];
            String preGuard = corrector.correctDeterministic(input); // == r[2]

            // (a) punctuator that ADDS punctuation only -> accepted (output contains punctuation,
            //     and stripping punctuation == preGuard).
            total++;
            OnDeviceCorrector.Punctuator addOnly = t -> insertCommas(t);
            String addOut = corrector.correct(input, addOnly);
            String addOutStripped = OnDeviceCorrector.stripPunct(addOut);
            if (addOut.contains("，") && addOutStripped.equals(preGuard)) {
                pass++;
            } else {
                fail++;
                failures.add("GUARD-add in=[" + input + "] expected punctuation accepted, got=[" + addOut + "]");
            }

            // (b) punctuator that ALTERS a character (drops/changes a non-punctuation char) ->
            //     guard must DISCARD it and return preGuard exactly.
            total++;
            OnDeviceCorrector.Punctuator altering = t -> {
                // change the first char to a different CJK char + add a comma (simulates hallucination)
                if (t.isEmpty()) return t;
                char first = t.charAt(0);
                char swapped = first == '債' ? '責' : '債';
                return swapped + "，" + t.substring(1);
            };
            String altOut = corrector.correct(input, altering);
            if (altOut.equals(preGuard)) {
                pass++;
            } else {
                fail++;
                failures.add("GUARD-alter in=[" + input + "] expected fallback to [" + preGuard
                        + "], got=[" + altOut + "]");
            }
        }

        // --- explicit unit checks for guard internals (independent of corpus) ---
        total++;
        if (OnDeviceCorrector.stripPunct("債權，人。對！債？務").equals("債權人對債務")) {
            pass++;
        } else {
            fail++;
            failures.add("stripPunct unit check failed: got=[" + OnDeviceCorrector.stripPunct("債權，人。對！債？務") + "]");
        }

        // --- null/empty robustness ---
        total++;
        boolean robust = corrector.correctDeterministic("") != null
                ? corrector.correctDeterministic("").isEmpty()
                : corrector.correctDeterministic("") == null;
        // empty input returns empty; null input returns null
        boolean nullOk = corrector.correctDeterministic(null) == null;
        if ("".equals(corrector.correctDeterministic("")) && nullOk) {
            pass++;
        } else {
            fail++;
            failures.add("empty/null robustness failed");
        }

        System.out.println("================ OnDeviceCorrector self-test ================");
        System.out.println("dict sizes: paraformer=" + dbgCount(corrector, "p")
                + " overrides=" + dbgCount(corrector, "o")
                + " mishear=" + dbgCount(corrector, "m")
                + " protected=" + dbgCount(corrector, "t"));
        System.out.println("total=" + total + "  pass=" + pass + "  fail=" + fail);
        if (fail > 0) {
            System.out.println("------------------ FAILURES ------------------");
            for (String f : failures) System.out.println(f);
            System.out.println("==============================================================");
            System.out.println("RESULT: FAIL");
            System.exit(1);
        }
        System.out.println("RESULT: PASS (all " + total + " cases green)");
    }

    // package-visible test accessors are package-private; reflect to read counts for the banner.
    static int dbgCount(OnDeviceCorrector c, String which) {
        try {
            java.lang.reflect.Method m;
            switch (which) {
                case "p": m = OnDeviceCorrector.class.getDeclaredMethod("paraformerRuleCount"); break;
                case "o": m = OnDeviceCorrector.class.getDeclaredMethod("legalOverrideRuleCount"); break;
                case "m": m = OnDeviceCorrector.class.getDeclaredMethod("mishearRuleCount"); break;
                default:  m = OnDeviceCorrector.class.getDeclaredMethod("protectedTermCount"); break;
            }
            m.setAccessible(true);
            return (int) m.invoke(c);
        } catch (Exception e) {
            return -1;
        }
    }

    static String insertCommas(String t) {
        // add a comma every 4 chars — punctuation only, no char change.
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < t.length(); i++) {
            sb.append(t.charAt(i));
            if (i > 0 && (i + 1) % 4 == 0 && i + 1 < t.length()) sb.append('，');
        }
        if (sb.length() > 0) sb.append('。');
        return sb.toString();
    }

    static InputStream in(String rel) throws Exception {
        return new FileInputStream(ASSETS.resolve(rel).toFile());
    }

    static List<String[]> loadCorpus() throws Exception {
        List<String[]> rows = new ArrayList<>();
        try (BufferedReader r = new BufferedReader(
                new InputStreamReader(new FileInputStream(CORPUS.toFile()), StandardCharsets.UTF_8))) {
            String line;
            while ((line = r.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') continue;
                String[] parts = line.split("\t", -1);
                if (parts.length < 3) continue;
                rows.add(new String[]{parts[0], parts[1], parts[2]});
            }
        }
        return rows;
    }
}
