import com.simon.voiceime.correct.OnDeviceCorrector;
import com.simon.voiceime.correct.TimeoutWall;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 * JVM self-test for {@link OnDeviceCorrector} — runs WITHOUT an Android device.
 *
 * Loads the §37-filtered APK asset dicts, runs ~50 Traditional-Chinese legal dictation cases
 * (golden expectations generated by tools/gen_selftest_corpus.py at server parity), and verifies:
 *   - 簡→繁 conversion (s2tw glyph, NOT s2twp)
 *   - the legal overrides (係爭→系爭, 程序 stays 程序, 准/準, 法律程序)
 *   - paraformer + legal_dict mishear fixes
 *   - protected-term no-touch
 *   - filler removal
 *   - the 改字 GUARD: a stub punctuator that ALTERS a character must be discarded (fallback to
 *     step-4 text); a stub that only ADDS punctuation must be accepted.
 *
 * Exit code 0 = all pass; non-zero = failures.
 */
public class OnDeviceCorrectorSelfTest {

    static final Path ASSETS = Paths.get("app/src/main/assets/correction");
    static final Path CORPUS = Paths.get("app/src/test/resources/selftest_corpus.tsv");

    public static void main(String[] args) throws Exception {
        OnDeviceCorrector corrector;
        try (InputStream para = in("paraformer_legal.txt");
             InputStream stp = in("opencc/STPhrases.txt");
             InputStream stc = in("opencc/STCharacters.txt");
             InputStream twv = in("opencc/TWVariants.txt");
             InputStream ovr = in("legal_overrides.txt");
             InputStream mis = in("legal_dict_mishear.txt");
             InputStream prot = in("protected_terms.txt")) {
            corrector = OnDeviceCorrector.load(para, stp, stc, twv, ovr, mis, prot);
        }

        List<String[]> rows = loadCorpus();
        int total = 0, pass = 0, fail = 0;
        List<String> failures = new ArrayList<>();

        // --- deterministic CASE rows (steps 1-4, no punctuation) ---
        for (String[] r : rows) {
            if (!"CASE".equals(r[0])) continue;
            total++;
            String input = r[1], expected = r[2];
            String got = corrector.correctDeterministic(input);
            if (expected.equals(got)) {
                pass++;
            } else {
                fail++;
                failures.add("CASE  in=[" + input + "]\n      exp=[" + expected + "]\n      got=[" + got + "]");
            }
        }

        // --- GUARD rows: feed a character-ALTERING punctuator -> must fall back to step-4 text. ---
        for (String[] r : rows) {
            if (!"GUARD".equals(r[0])) continue;
            String input = r[1];
            String preGuard = corrector.correctDeterministic(input); // == r[2]

            // (a) punctuator that ADDS punctuation only -> accepted (output contains punctuation,
            //     and stripping punctuation == preGuard).
            total++;
            OnDeviceCorrector.Punctuator addOnly = t -> insertCommas(t);
            String addOut = corrector.correct(input, addOnly);
            String addOutStripped = OnDeviceCorrector.stripPunct(addOut);
            if (addOut.contains("，") && addOutStripped.equals(preGuard)) {
                pass++;
            } else {
                fail++;
                failures.add("GUARD-add in=[" + input + "] expected punctuation accepted, got=[" + addOut + "]");
            }

            // (b) punctuator that ALTERS a character (drops/changes a non-punctuation char) ->
            //     guard must DISCARD it and return preGuard exactly.
            total++;
            OnDeviceCorrector.Punctuator altering = t -> {
                // change the first char to a different CJK char + add a comma (simulates hallucination)
                if (t.isEmpty()) return t;
                char first = t.charAt(0);
                char swapped = first == '債' ? '責' : '債';
                return swapped + "，" + t.substring(1);
            };
            String altOut = corrector.correct(input, altering);
            if (altOut.equals(preGuard)) {
                pass++;
            } else {
                fail++;
                failures.add("GUARD-alter in=[" + input + "] expected fallback to [" + preGuard
                        + "], got=[" + altOut + "]");
            }
        }

        // --- LLM-punctuator cage tests (independent of corpus) -----------------------------------
        // Model "output style": ChatML-ish, punctuation inserted. The cage must accept punctuation-
        // only changes and REJECT any non-punctuation char change — incl. simplified-char drift and
        // legal-term alteration — regardless of what the model returns.
        {
            String pre = corrector.correctDeterministic("被告應給付原告新台幣一百萬元");

            // (1) LLM inserts only punctuation -> ACCEPT.
            total++;
            OnDeviceCorrector.Punctuator llmGood = t -> t + "。"; // append a period
            String g1 = corrector.correct("被告應給付原告新台幣一百萬元", null, llmGood);
            if (g1.endsWith("。") && OnDeviceCorrector.stripPunct(g1).equals(pre)) pass++;
            else { fail++; failures.add("LLM-cage punctuation-only should be accepted, got=[" + g1 + "]"); }

            // (2) LLM injects a SIMPLIFIED char (应 for 應) while adding punctuation -> REJECT.
            //     Proves simplified-drift is structurally impossible regardless of base model.
            total++;
            OnDeviceCorrector.Punctuator llmSimp = t -> t.replace("應", "应") + "。";
            String g2 = corrector.correct("被告應給付原告新台幣一百萬元", null, llmSimp);
            if (g2.equals(pre)) pass++; // rejected -> falls back to deterministic (no punctuation)
            else { fail++; failures.add("LLM-cage simplified-drift should be REJECTED, got=[" + g2 + "]"); }

            // (3) LLM drops a character -> REJECT.
            total++;
            OnDeviceCorrector.Punctuator llmDrop = t -> t.substring(1) + "。";
            String g3 = corrector.correct("被告應給付原告新台幣一百萬元", null, llmDrop);
            if (g3.equals(pre)) pass++;
            else { fail++; failures.add("LLM-cage char-drop should be REJECTED, got=[" + g3 + "]"); }

            // (4) CHAIN: LLM (primary) hallucinates a char-change -> rejected; CT-Transformer-style
            //     fallback (punctuation-only) -> accepted. Proves graceful degradation within ONE call.
            total++;
            OnDeviceCorrector.Punctuator badPrimary = t -> "X" + t; // char added -> reject
            OnDeviceCorrector.Punctuator goodFallback = t -> insertCommas(t); // punctuation only
            String g4 = corrector.correct("被告應給付原告新台幣一百萬元", null, badPrimary, goodFallback);
            if (OnDeviceCorrector.stripPunct(g4).equals(pre) && !g4.equals(pre)) pass++;
            else { fail++; failures.add("CHAIN should fall back primary->fallback, got=[" + g4 + "]"); }

            // (5) CHAIN: both reject -> deterministic (no punctuation).
            total++;
            OnDeviceCorrector.Punctuator badA = t -> "甲" + t;
            OnDeviceCorrector.Punctuator badB = t -> t.substring(1);
            String g5 = corrector.correct("被告應給付原告新台幣一百萬元", null, badA, badB);
            if (g5.equals(pre)) pass++;
            else { fail++; failures.add("CHAIN both-reject should return deterministic, got=[" + g5 + "]"); }

            // (6) context overload is reachable (default method delegates); a context-only impl that
            //     ignores ctx and adds punctuation is accepted.
            total++;
            OnDeviceCorrector.Punctuator ctxAware = new OnDeviceCorrector.Punctuator() {
                public String addPunctuation(String t) { return t; }
                public String addPunctuation(String t, String ctx) { return t + "！"; }
            };
            String g6 = corrector.correct("被告應給付原告新台幣一百萬元", "前文範例", ctxAware);
            if (g6.endsWith("！") && OnDeviceCorrector.stripPunct(g6).equals(pre)) pass++;
            else { fail++; failures.add("context-aware punctuator should be accepted, got=[" + g6 + "]"); }
        }

        // --- explicit unit checks for guard internals (independent of corpus) ---
        total++;
        if (OnDeviceCorrector.stripPunct("債權，人。對！債？務").equals("債權人對債務")) {
            pass++;
        } else {
            fail++;
            failures.add("stripPunct unit check failed: got=[" + OnDeviceCorrector.stripPunct("債權，人。對！債？務") + "]");
        }

        // --- null/empty robustness ---
        total++;
        boolean robust = corrector.correctDeterministic("") != null
                ? corrector.correctDeterministic("").isEmpty()
                : corrector.correctDeterministic("") == null;
        // empty input returns empty; null input returns null
        boolean nullOk = corrector.correctDeterministic(null) == null;
        if ("".equals(corrector.correctDeterministic("")) && nullOk) {
            pass++;
        } else {
            fail++;
            failures.add("empty/null robustness failed");
        }

        // --- v6.9.2 TIMEOUT WALL tests (the GUARANTEE) ------------------------------------------
        // Proves: a correction/punctuator that BLOCKS longer than the budget must NOT block the
        // caller — the wall returns the fallback (the preview text the user already sees) within
        // the budget. Also covers normal completion, exceptions, and empty results.
        {
            final long BUDGET = 300L; // small budget so the test is fast; real path uses 2000ms.
            final String PREVIEW = "被告應給付原告新台幣一百萬元"; // stand-in for currentAppendPreviewText()

            // (T1) Task HANGS far past budget (simulates the hung LLM nativeComplete) -> wall must
            //      return the PREVIEW fallback, and must do so WITHIN the budget (not block on hang).
            total++;
            long w0 = System.currentTimeMillis();
            String hung = TimeoutWall.runWithBudget(() -> {
                Thread.sleep(BUDGET * 20); // 6s — would freeze the keyboard without the wall
                return "校正後文字（永遠不會回來）";
            }, PREVIEW, BUDGET);
            long elapsed = System.currentTimeMillis() - w0;
            // committed text == preview (uncorrected), and we did NOT wait for the hung worker.
            if (PREVIEW.equals(hung) && elapsed < BUDGET + 800) {
                pass++;
            } else {
                fail++;
                failures.add("TIMEOUT-WALL hang: expected fallback=[" + PREVIEW + "] within "
                        + (BUDGET + 800) + "ms, got=[" + hung + "] in " + elapsed + "ms");
            }

            // (T2) Task completes WELL within budget with a real corrected string -> return it.
            total++;
            String ok = TimeoutWall.runWithBudget(() -> PREVIEW + "。", PREVIEW, BUDGET);
            if ((PREVIEW + "。").equals(ok)) pass++;
            else { fail++; failures.add("TIMEOUT-WALL fast-path: expected corrected text, got=[" + ok + "]"); }

            // (T3) Task THROWS -> wall must swallow and return fallback (never propagate).
            total++;
            String threw = TimeoutWall.runWithBudget(() -> { throw new RuntimeException("boom"); },
                    PREVIEW, BUDGET);
            if (PREVIEW.equals(threw)) pass++;
            else { fail++; failures.add("TIMEOUT-WALL throw: expected fallback, got=[" + threw + "]"); }

            // (T4) Task returns null/empty -> treated as "produced nothing" -> fallback.
            total++;
            String nullRes = TimeoutWall.runWithBudget(() -> null, PREVIEW, BUDGET);
            String emptyRes = TimeoutWall.runWithBudget(() -> "", PREVIEW, BUDGET);
            if (PREVIEW.equals(nullRes) && PREVIEW.equals(emptyRes)) pass++;
            else { fail++; failures.add("TIMEOUT-WALL null/empty: expected fallback, got null=[" + nullRes
                    + "] empty=[" + emptyRes + "]"); }

            // (T5) END-TO-END: a real OnDeviceCorrector whose injected punctuator HANGS. The whole
            //      correct(...) call is run under the wall; the guarantee is that SOME non-empty text
            //      comes back within budget (here the preview), proving no path blocks forever even if
            //      a punctuator hangs (defense-in-depth for any future LLM re-enable).
            total++;
            OnDeviceCorrector.Punctuator hangingPunct = new OnDeviceCorrector.Punctuator() {
                public String addPunctuation(String t) {
                    try { Thread.sleep(BUDGET * 20); } catch (InterruptedException ignored) {}
                    return t + "。";
                }
            };
            long e0 = System.currentTimeMillis();
            String e2e = TimeoutWall.runWithBudget(
                    () -> corrector.correct(PREVIEW, null, hangingPunct), PREVIEW, BUDGET);
            long e2eMs = System.currentTimeMillis() - e0;
            if (PREVIEW.equals(e2e) && e2eMs < BUDGET + 800) pass++;
            else { fail++; failures.add("TIMEOUT-WALL e2e-hang: expected fallback within budget, got=["
                    + e2e + "] in " + e2eMs + "ms"); }
        }

        System.out.println("================ OnDeviceCorrector self-test ================");
        System.out.println("dict sizes: paraformer=" + dbgCount(corrector, "p")
                + " overrides=" + dbgCount(corrector, "o")
                + " mishear=" + dbgCount(corrector, "m")
                + " protected=" + dbgCount(corrector, "t"));
        System.out.println("total=" + total + "  pass=" + pass + "  fail=" + fail);
        if (fail > 0) {
            System.out.println("------------------ FAILURES ------------------");
            for (String f : failures) System.out.println(f);
            System.out.println("==============================================================");
            System.out.println("RESULT: FAIL");
            System.exit(1);
        }
        System.out.println("RESULT: PASS (all " + total + " cases green)");
    }

    // package-visible test accessors are package-private; reflect to read counts for the banner.
    static int dbgCount(OnDeviceCorrector c, String which) {
        try {
            java.lang.reflect.Method m;
            switch (which) {
                case "p": m = OnDeviceCorrector.class.getDeclaredMethod("paraformerRuleCount"); break;
                case "o": m = OnDeviceCorrector.class.getDeclaredMethod("legalOverrideRuleCount"); break;
                case "m": m = OnDeviceCorrector.class.getDeclaredMethod("mishearRuleCount"); break;
                default:  m = OnDeviceCorrector.class.getDeclaredMethod("protectedTermCount"); break;
            }
            m.setAccessible(true);
            return (int) m.invoke(c);
        } catch (Exception e) {
            return -1;
        }
    }

    static String insertCommas(String t) {
        // add a comma every 4 chars — punctuation only, no char change.
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < t.length(); i++) {
            sb.append(t.charAt(i));
            if (i > 0 && (i + 1) % 4 == 0 && i + 1 < t.length()) sb.append('，');
        }
        if (sb.length() > 0) sb.append('。');
        return sb.toString();
    }

    static InputStream in(String rel) throws Exception {
        return new FileInputStream(ASSETS.resolve(rel).toFile());
    }

    static List<String[]> loadCorpus() throws Exception {
        List<String[]> rows = new ArrayList<>();
        try (BufferedReader r = new BufferedReader(
                new InputStreamReader(new FileInputStream(CORPUS.toFile()), StandardCharsets.UTF_8))) {
            String line;
            while ((line = r.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') continue;
                String[] parts = line.split("\t", -1);
                if (parts.length < 3) continue;
                rows.add(new String[]{parts[0], parts[1], parts[2]});
            }
        }
        return rows;
    }
}
