package com.simon.voiceime;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class Observer677R2Test {
static boolean isTapCandidate(Object tag){return tag instanceof ZhuyinInputController.TextChoice&&((ZhuyinInputController.TextChoice)tag).start>=0&&((ZhuyinInputController.TextChoice)tag).boundary==-1;}
static boolean isExternalCandidate(Object tag){return tag instanceof ZhuyinInputController.TextChoice&&((ZhuyinInputController.TextChoice)tag).boundary==-1;}
static Object nativeRange(){return new ZhuyinInputController.TextChoice("波","char","波","ㄅ",1,0,true,false,0,1);}
static Object tap(){return new ZhuyinInputController.TextChoice("願","char","院","",-1,-1,false,false,8,9);}
static Object selection(){return new ZhuyinInputController.TextChoice("時見","word","時間","",-1,-1);}
@Test public void site0(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testTapRowsAndCharacterReplacement#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testTapRowsAndCharacterReplacement#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site1(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testKeyboardCommitAndDeleteDoNotTriggerTapRows#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testKeyboardCommitAndDeleteDoNotTriggerTapRows#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site2(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testKeyboardCommitAndDeleteDoNotTriggerTapRows#2: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testKeyboardCommitAndDeleteDoNotTriggerTapRows#2: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site3(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testPasswordCaretOffersNoTapRows#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testPasswordCaretOffersNoTapRows#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site4(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site5(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#2: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#2: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site6(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#3: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testHideReopenAndFieldSwitchClearRows#3: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site7(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testUnreadableTapIsSilent#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testUnreadableTapIsSilent#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site8(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testFailedReplacementRestoresOriginalCaret#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testFailedReplacementRestoresOriginalCaret#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site9(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("ExternalSelection675AndroidTest.testChangedSelectionAndEditDiscardPendingCandidates#1: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isExternalCandidate));tags=Arrays.asList(tap());assertTrue("ExternalSelection675AndroidTest.testChangedSelectionAndEditDiscardPendingCandidates#1: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isExternalCandidate));}
@Test public void site10(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.awaitTapRows: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.awaitTapRows: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void site11(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("ExternalSelection675AndroidTest.awaitCandidateCount: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isExternalCandidate));tags=Arrays.asList(tap());assertTrue("ExternalSelection675AndroidTest.awaitCandidateCount: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isExternalCandidate));}
@Test public void site12(){List<Object> tags=Arrays.asList(nativeRange(),"native-next-word",null);assertFalse("TapCursor677AndroidTest.testScrolledCandidateReplacement: native candidates are not external",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));tags=Arrays.asList(tap());assertTrue("TapCursor677AndroidTest.testScrolledCandidateReplacement: real external must still be detected",tags.stream().anyMatch(Observer677R2Test::isTapCandidate));}
@Test public void nativePreviewRangesAreNotCommittedTapCandidates(){assertFalse(isTapCandidate(nativeRange()));assertTrue(isTapCandidate(tap()));assertFalse(isTapCandidate("native-next-word"));assertFalse(isTapCandidate(null));}
@Test public void selectedSpanTransactionIsNotLost(){assertTrue("6.76 selection lacks start range but remains external",isExternalCandidate(selection()));assertTrue(isExternalCandidate(tap()));assertFalse(isExternalCandidate(nativeRange()));}
}